# Generated by Django 5.0.1 on 2024-06-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='brand',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
