# Generated by Django 5.0.1 on 2024-06-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_shirt_is_bestseller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=48)),
                ('image', models.ImageField(upload_to='')),
                ('brand', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
