# Generated by Django 5.0.1 on 2024-06-09 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
